app:
  api:
    resource: api.js
    cache: api.json
    remote_attribute: '@remote'
    form_attribute: '@form'
    url: /
    type: remoting
    namespace: Action
    variable: Ext.app.REMOTING_API
  response:
    default_resource: ui/web/index.html
    views_location: views/
  lib:
    extjs: lib/ui/extjs/